### ISSUE TITLE
Crash relating to Midnight's biomes and pathfinding

### ISSUE THREAD

**Issue by cybercat5555** [Cryptic-Mushroom/The-Midnight#193]
The Midnight 0.2.0
Forge .2796

Shortly after entering The Midnight, I got a crash relating biomes and pathfinding

Crash log:
[crash-2019-02-10_16.31.43-server.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/2849426/crash-2019-02-10_16.31.43-server.txt)

**Comment by cybercat5555** [comment]
Adding to this, not sure if its connected to the above, but I got this crash after trying to restart the game

Crash: 
[crash-2019-02-10_18.24.19-client.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/2849528/crash-2019-02-10_18.24.19-client.txt)

**Comment by Andromander** [comment]
The first one appears to be a server crash caused by the decorator attempting to decorate more than once. The second is because Dim -23 appears to have been registered already by another mod. For the latter crash, try checking the configs of other mods that add dimensions and adjust the IDs where needed.

I have a theory that the two IDs clashing could also have caused a crash with the decorator, but that's yet to be seen

**Comment by five0five** [comment]
Referring to Androsa's comment up there ^ -23 is the ID of the 'darkness lair' in fossils and archaeology

**Comment by five0five** [comment]
presumably this was resolved? if you're still encountering it, reopen
