### ISSUE TITLE
OpenAL Audio Issue

### ISSUE THREAD

**Issue by ejektaflex** [Cryptic-Mushroom/The-Midnight#235]
![AL](https://user-images.githubusercontent.com/23628421/58609410-14970b00-826d-11e9-89d7-1873cc328482.PNG)

When playing, this constantly gets spammed in the console. I'd post a log, however it's enormous and only shows this, because it spams the chat many times per second.

Midnight 0.3.3
Forge 14.23.5.2838 (This is the min-ver for another mod, otherwise I would use latest recommended)

**Comment by Jonathing** [comment]
This does not seem to be an issue with The Midnight mod. Since there are no log events from the mod itself, I can only assume that the OpenAL error is coming from a mishap in either Forge or your machine's incompatibility with the sound system.

If you can somehow link this error back to the Midnight mod, I'm happy to take a look. Until then, this issue will be closed.
