### ISSUE TITLE
Crash with 1.14.4

### ISSUE THREAD

**Issue by vico93** [Cryptic-Mushroom/The-Midnight#292]
[Log](https://paste.dimdev.org/jiruyoqisa.md)

Using MC 1.14.4, Forge 28.0.83 and Midnight 0.4.4

**Comment by littlett98** [comment]
midnight 0.4.4 is made to run on 28.0.45-28.0.51. The devs are in the process of updating the mod to run on forge versions 28.0.75 and above

**Comment by Commoble** [comment]
On the subject of crashes in Forge 28.0.83: Forge 83 made a small change to login packet registry that breaks the S2CDimensionSync here: https://github.com/Cryptic-Mushroom/The-Midnight/blob/1.14.4-dev/src/main/java/com/mushroom/midnight/common/registry/MidnightDimensions.java

This can be fixed by making two adjustments:

1) make S2CDimensionSync implement IntSupplier
2) add this method to the class:
`		@Override
		public int getAsInt()
		{
			return this.getLoginIndex();
		}`

**Comment by Sunekaer** [comment]
Same issue https://paste.dimdev.org/adavujajox.sql

**Comment by gegy1000** [comment]
This will be fixed in the next release :)
