### ISSUE TITLE
No portals spawning in my world 1.14.4

### ISSUE THREAD

**Issue by Otter420** [Cryptic-Mushroom/The-Midnight#293]
I played with this mod for a couple of time now and i have never seen any portal spawning in my survival world. I also use the "Better Animations Mod" and the "lucky Blocks Mod".
In my creative world the mod works and i can use the blocks included in the mod.

greetings, Otter420

**Comment by littlett98** [comment]
In your survival world, did you generate the world before adding the mod?

I have the same issue since I generated my world before adding the midnight.

The devs are adding a config file to work in the issue. 

For now /summon midnight:rift is the best way to access the midnight if you can't find a rift.

**Comment by Jammeram** [comment]
Is there a way to spawn a rift in the 1.15.2 version of the mod?

**Comment by Jonathing** [comment]
@Jammeram They spawn as structures now. You can find one using `/locate midnight:entrance_rift`

**Comment by Jammeram** [comment]
thank you very much!

**Comment by Jonathing** [comment]
The Midnight for Minecraft 1.14.4 is no longer supported. If you believe that this issue still exists in the 1.15.2 version of the mod, feel free to reopen the issue and provide examples as to how that is.
