### ISSUE TITLE
Archaic Glass Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [Cryptic-Mushroom/The-Midnight#327]
`Minecraft v1.14.4`
`Forge v28.1.90`
`The Midnight v0.4.6`

The Archaic Glass currently renders incorrectly when placed underwater. It displays flowing water on it's sides.

**Comment by RedGalaxySW** [comment]
This is not a compat issue, just a rendering bug...

**Comment by RedGalaxySW** [comment]
Solving this in 1.14.4 requires a coremod hook or a completely rewrite of the block/fluid renderer to support overlays of midnight blocks (it's hardcoded)... We were able to fix it in 1.15.2 as a hook seems to exist in that version. In the LTS version (1.14.4) this doesn't exist yet. Once it does and we want to support that specific Forge version, this can be fixed in 1.14.4 too...

**Comment by RedGalaxySW** [comment]
Ok a small hack made us able to still fix this in 1.14.4... I'll close it now...
