### ISSUE TITLE
Hour 1 feedback - Where's the hook?

### ISSUE THREAD

**Issue by trevorjd** [Cryptic-Mushroom/The-Midnight#331]
Hi! Firstly, I genuinely recognise and appreciate the hard work you've A. put in and B. chosen to share with us at _**no cost**_. I've dabbled in modding. I know how much work this is. Even as a labour of love, it still feels good to get recognised, so here 'tis. Good work! A sincere thank you for your efforts and generosity!

Now the 'but', the (hopefully constructive!) criticism. I've been in the Midnight for about an hour now. What's the point? The soundtrack and darkness are driving me to despair. I have Major Depressive Disorder. I play minecraft for _fun_, not deep introspective into the human condition; I get enough of that shit every day of my existence. Constant darkness and creepy neverending-tones seem to be all the rage but they're not for me.

I've beaten off the rifters around my base several times but watching Tuba Skinny on YT meant that I (and my llama) got abducted about an hour ago. OK, let's check out what this has to offer... oh! A REALLY FUCKING ANNOYING soundtrack. Excellent! Nice start!

The rifters try to kill me instead of abduct me. OK... so why did they abduct me? Just to kill me on more familiar turf? They could've killed me back in the overworld! A few endermen, which is nice, since I don't have a regular supply of pearls at the moment. A few trees, mushrooms, dirt, stone, most of which are vanilla equivalents or can't be used for anything interesting (according to JEI) . Rifters drop no loot. The (dusk lurkers?) (rare) drop an item that's 1:1 with cow leather. Cows don't try to eat me. The Hunters (very rare) drop a 12+ food item which is nice but... after an hour I've only encountered 1 so filed under "cute but can't be relied on". Crystals (and bugs) that seem to be cosmetic only.

It may be that there's a purpose to all this stuff, but having been in this dimension for an hour and having not received any clues as to _**why**_, what reason to stay here, or how to get home, I'm just going to die, respawn at home and uninstall the mod.

Moving forward, I suggest you add something to the mod that explains to the player how to get started in the mod. I'm sure I could learn more from google but IMO _we shouldn't need to meta-game_. Meta-gaming sucks! I got your mod by virtue of downloading FTB Unstable. The thing about kitchen-sink packs like Unstable is that, generally, you can simply ignore mods that you don't want to play. Since you can get sucked into the Midnight despite lack of desire to play the mod, you might want to implement some kind of easy-return method :-)

Also, you owe me one llama :-(

**Comment by cipherzerox** [comment]
Hey, Trevor! Thank you for your feedback. It was definitely constructive (though I will say that some things came across a bit rude, but all is forgiven xD). 
That aside, we've been working on an update that will overhaul rifts so one of the perks will be easy return. For a while now we've been on hiatus just due to life unfortunately, though we have put out a few patches (maybe less) in the last few months. It won't be out any time soon unless another coder or two can offer consistent help, so that's nice.
However, your feedback could not have come at a better time! I just got over some burnout and I've been needing to dive back into designing content for Midnight for a while now, so I definitely should start at these points.
Thank you so much! (and work on your presentation because many people probably wouldn't be so nice xD)

**Comment by trevorjd** [comment]
I promise you that none of it was intended as rude but I'm someone who doesn't believe in "sugar-coating stuff to the point that it's meaningless" which seems to be the spirit of the age. I'm very glad that you've accepted my thoughts in good faith.

Again, thank you for offering up the fruits of your labour of love. I genuinely know how much work is involved.

**Comment by trevorjd** [comment]
but yes, I recognise that my delivery could've been more delicate.
