### ISSUE TITLE
Server console spam

### ISSUE THREAD

**Issue by nodogsleft** [Cryptic-Mushroom/The-Midnight#355]
Whenever I join the server, the console immediately spams with "chunks saved" multiple times each second for the midnight dimension. This does not occur with any other dimension, and ceases when I enter the actual dimension. Upon leaving, the spam will resume once again. I can't seem to replicate the issue without the other mods, or even in singleplayer. This seems to be unique to this one server.

> [22Mar2020 02:55:39.711] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (midnight): All chunks are saved

I attempted removing my player data and reloading, but that didn't fix the issue either. I'm really not sure on what to do next.

https://pastebin.com/i2BnBbWy
https://pastebin.com/ci10T2ec
https://pastebin.com/Ybvh2ghZ -contains the actual spam
please excuse the naming.

**Comment by Jonathing** [comment]
I've tried to reproduce this bug, but I can't. It might be caused by another mod, but you have too many mods installed for me to figure out which one it is. If you are able to, try narrowind down the mods you have and see if the issue persists. Re-open this issue if you decide to do so. If you're able to narrow it down to a single mod, that'd be fantastic.
