### ISSUE TITLE
Biomes O' Plenty combatibility

### ISSUE THREAD

**Issue by xxfinemus** [Cryptic-Mushroom/The-Midnight#376]
When using this mod together with Biomes O' Plenty I cannot get the portal structure to spawn reliably, and it only appears in vanilla biomes. 

I might add this is tested on
Minecraft version: 1.15.2
Forge version: 31.1.37
Mod version: 0.5.4
Biomes O' Plenty version: 10.0.0.345

**Comment by Jonathing** [comment]
That's weird. I made sure to have it spawn specifically in biomes o plenty biomes as well. I have free time later today, so I'll test for the issue and if I can reproduce it, I'll go ahead and fix the issue.

**Comment by Amcro** [comment]
I'm not sure if i'm doing something wrong but i'm still missing rifts.. can't use /summon midnight:rift command as if rift is not existent, i've tried to completely remove the mod and config and reinstalling it. didn't solve the issue. I'm using TerraForged along with BOP but i don't think it matters since i cannot even spawn it myself. I did update the mod to latest version, i'm up for testing and helping you to solve the issue.

**Comment by xxfinemus** [comment]
Which version of the mod are you using?
Because in the newest versions of this mod it is my understanding, that they removed rift spawning and the command you are referring to. Instead now structures spawn in that can be used as portals to the midnight. And in place of the rift spawning command, you can use a dark pearl to spawn in the portal structure.

**Comment by Amcro** [comment]
@xxfinemus you're right dark pearl spawns portal structure and i can get to the midnight dimension but i still haven't found single portal using TerraForged and BOP mod together, i'm gonna try to find it tomorrow and i'll report here after the search

**Comment by Jonathing** [comment]
We're still having issues with TerraForged compatibility. You can follow that thread in issue #406.
