### ISSUE TITLE
Crashes when attempting to enter the dimension with the Reliquary mod

### ISSUE THREAD

**Issue by SpencerMeow** [Cryptic-Mushroom/The-Midnight#414]
It crashes the game for some reason, heres the log (I think) 
[crash-2020-06-07_11.37.52-client.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/4742496/crash-2020-06-07_11.37.52-client.txt)

**Comment by Jonathing** [comment]
Right now, mod compatibility is not our top priority, as we will soon be working on the rewrite for 1.16. Also, your log looks like it's a fault in the Reliquary mod because I don't see The Midnight anywhere in the stacktrace. Make sure to also open an issue on their issue tracker to see what the problem is because the error log doesn't really tell me much.

**Comment by Jonathing** [comment]
we don't support 1.12.2. please update your game.
![https://cdn.moddinglegacy.com/241863583330333866-msedge_FDAjlay7Zw.png](https://cdn.moddinglegacy.com/241863583330333866-msedge_FDAjlay7Zw.png)
