### ISSUE TITLE
[crash] Game can't launch with Midnight installed

### ISSUE THREAD

**Issue by Rafii2198** [Cryptic-Mushroom/The-Midnight#435]
# The Crash

Each time I launch the game with The Midnight, I am getting message from forge:
**The Midnight (midnight) encountered an error during the common_setup event phase**
null

Screenshot: 
![image](https://user-images.githubusercontent.com/26695327/95498246-d141c600-09a3-11eb-8ca3-7eec89de876b.png)

# Steps to reproduce

Literally, anytime, no matter if I have other mods or just Midnight, Forge gives me that error
# Important Notes

The game is not considered as crashed as there are no crash logs.
Here is the latest.log file, maybe this can help: https://pastebin.pl/view/55721e9b

## Environment

- Minecraft: 1.15.2
- Midnight: 0.5.9
- Forge: 32.2.36 (Although tested with some newer versions including current latest)
- Launcher: MultiMC
- OS: Arch Linux (maybe also it is because I am using Linux, my friends on windows are playing normally)

**Comment by Jonathing** [comment]
Try the following few things:
- Make sure you're running on Java 8. There are some methods we use in Java 8 that have been moved or refactored in Java 11+.
- Try running the game on Forge's *recommended* build.

The error that is in your `latest.log` file has something to do with the fact that your game cannot access a method from JDK, so it's possible that Forge might've changed something since the recommended build, or you aren't using Java 8.

**Comment by Jonathing** [comment]
This issue has been left open for 5 days without any interaction, so I will be closing it. If this issue still persists and you've done what I asked earlier, feel free to reopen it.
