### ISSUE TITLE
Hunter AI needs fixing

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#71]
They seems to just love running into walls and flying endlessly into the midnight sky instead of taking out prey, I love the concept of this mob but its AI makes it seem like it failed preschool.

**Comment by gegy1000** [comment]
It's not released within reason. ;)

**Comment by ScytheIronclaw** [comment]
I find the hunters to be very annoying. They have a lot of health, can quickly catch up to a sprinting player, and unless some sort of ranged weapon besides the spiked throwable mushrooms is added, it's a real pain to kill them off because you have such a small window of opportunity to attack them. Finally they hit you with a status effect that quickly drains your health. It would be great if there was a config option to change their rate of spawn.

**Comment by five0five** [comment]
Assuming you want to completely remove them, you can use the Bad Mobs mod to disable them. The status effect only works under the condition you're moving, stand still and you won't take any damage. I'm pretty sure they're a bit less common next patch, too.

**Comment by five0five** [comment]
closing for now since this is on our trello to do
